import { addKeyword, EVENTS } from "@builderbot/bot";

export const opcion7rentaServerPrincipalesBoxFlow = addKeyword(EVENTS.ACTION)
    .addAnswer([
        'renta server de las principales box',
        '*ALQUILER 24/7*',
        '*1* EFT PRO',
        '*2* HYDRATOO',
        '*3* NCK BOX + UMT',
        '*4* BE NCK DONGLE + UMT',
        '*5* OCTOPLUS FRP',
        '*6* SIGMA BOX 3-4-5',
        '*7* Z3X SAM',
        '*8* Z3X SAM 2',
        '*9* EFT PRO',
        '*10* EFT PRO 2',
        '*11* HYDRA',
        '*12* NCK-UMT HORA QUITO',
        '*13* OCTO HUAWEI',
        '*14* OCTO LG',
        '*15* OCTO SAM',
        '*16* SIGMA PLUS',
        '*17* SIGMA PLUS',
        '*18* UMT-AVENGER-NCK HUAWEI',
        '*19* UMT-AVENGER-NCK HUAWEI S2',
        '*20* Z3X 1',
        '*21* Z3X 2',
        '*22* Z3X 3',
        '*23* halabtech✅',
        '*24* easy-firmware.com✅',
        '*25* https://easyfirmwares.com/✅',
        '*26* https://www.needrom.com/✅',
        '*27* https://downloadgsm.com/✅',
    ])
    .addAnswer([
        '*se renta por separado*',
        '1 unlock tools 24 horas',
        'cheata 24 horas',
        'e-gsm 24 horas',
        'chimera pro',
        'tr tools',
        'dft pro',
        'preguntar stop',
    ])